// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: server/v1/health.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HealthAPIClient is the client API for HealthAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthAPIClient interface {
	// This endpoint can be used to check the liveness of the server.
	Health(ctx context.Context, in *HealthCheckInput, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type healthAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthAPIClient(cc grpc.ClientConnInterface) HealthAPIClient {
	return &healthAPIClient{cc}
}

func (c *healthAPIClient) Health(ctx context.Context, in *HealthCheckInput, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/HealthAPI/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthAPIServer is the server API for HealthAPI service.
// All implementations should embed UnimplementedHealthAPIServer
// for forward compatibility
type HealthAPIServer interface {
	// This endpoint can be used to check the liveness of the server.
	Health(context.Context, *HealthCheckInput) (*HealthCheckResponse, error)
}

// UnimplementedHealthAPIServer should be embedded to have forward compatible implementations.
type UnimplementedHealthAPIServer struct {
}

func (UnimplementedHealthAPIServer) Health(context.Context, *HealthCheckInput) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}

// UnsafeHealthAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthAPIServer will
// result in compilation errors.
type UnsafeHealthAPIServer interface {
	mustEmbedUnimplementedHealthAPIServer()
}

func RegisterHealthAPIServer(s grpc.ServiceRegistrar, srv HealthAPIServer) {
	s.RegisterService(&HealthAPI_ServiceDesc, srv)
}

func _HealthAPI_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthAPIServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HealthAPI/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthAPIServer).Health(ctx, req.(*HealthCheckInput))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthAPI_ServiceDesc is the grpc.ServiceDesc for HealthAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "HealthAPI",
	HandlerType: (*HealthAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _HealthAPI_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/v1/health.proto",
}
