name: go-lint
on:
  push:
  workflow_call:
    secrets:
      API_DEPLOY_KEY:
        required: true
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH deploy keys
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.API_DEPLOY_KEY }}
          
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'
          
      - name: Install test deps
        run: |
          /bin/bash scripts/install_build_deps.sh
          /bin/bash scripts/install_test_deps.sh
          
      - name: Generated code
        run: make generate mock
        
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.45.2
          skip-pkg-cache: true
          skip-build-cache: true
