name: go-test
on:
  push:
  workflow_call:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.2'

      - name: Install test deps
        run: |
          /bin/bash scripts/install_build_deps.sh
          /bin/bash scripts/install_test_deps.sh

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Run tests
        run: TEST_PARAM="-coverprofile=coverage.out -covermode=atomic" make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
