name: release
on:
  push:
    branches:
      - "alpha"
      - "beta"
      - "rc"
      - "release"
jobs:
  test:
    uses: ./.github/workflows/go-test.yaml
    secrets:
      API_DEPLOY_KEY: ${{ secrets.API_DEPLOY_KEY }}
  lint:
    uses: ./.github/workflows/go-lint.yaml
    secrets:
      API_DEPLOY_KEY: ${{ secrets.API_DEPLOY_KEY }}
  release:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --debug
